### PR TITLE
Glorious geckos token info mint address correction

### PR DESCRIPTION
**Pull request by GloriousXican**
---
# Please note: This repository is being rebuilt to accept the new volume of token additions and modifications. PR merges will be delayed.
---

## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

## Auto merge requirements

Your pull request will be automatically merged if the following conditions are met:

- Your pull request **only adds new tokens** to the list. Any modification to existing
  tokens will require manual review to prevent unwanted modifications.

- Your pull request does **not touch unrelated code**. In particular, reformatting changes to unrelated
  code will cause the auto merge to reject your PR.

- Any **asset files added correspond to the token address** you are adding. Asset files
  must be PNG, JPG or SVG files.

- Your change is **valid JSON** and **conforms to the schema**. If your change failed validation,
  read the error message carefully and update your PR accordingly.

- No other tokens shares the **same name, symbol or address**.

For example, this change would be rejected due to unrelated changes:

The bot runs **every 60 minutes** and bulk-merges all open pull requests to prevent conflicts.
This means that you need to wait up to 60 minutes for your pull request to be merged or reprocessed.

### CODE REVIEW

**Comment by GloriousXican** [comment]
I just need to change the mint address because it was not correct, so the info of the token was not showing accordingly.

**Comment by SolanaTokenMerger** [comment]
You need to open a New issue and link your PR to let Solana Developers manually merge it!! Hope this did help you!! If you do have any kind of questions, don't hesitate writing me!!

**Comment by keone** [comment]
`duplicate token: token name GLORIOUS GECKOS is already used`

please delete the old one (HTr5SoWycrUdHbbrRQvxe9qhVraP196p8At7LrfPbpmr)

**Comment by GloriousXican** [comment]
﻿Hello! GM

My apologies, how do I delete that address in dexlab.minting or do you mean by Github Repo?

Thank you for your support

El 19 feb 2022, a la(s) 10:12 a.m., keone ***@***.***> escribió:

﻿

duplicate token: token name GLORIOUS GECKOS is already used

please delete the old one (HTr5SoWycrUdHbbrRQvxe9qhVraP196p8At7LrfPbpmr)

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsolana-labs%2Ftoken-list%2Fpull%2F19128%23issuecomment-1046051812&data=04%7C01%7C%7C504913588ce946da1dcb08d9f3c2a102%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637808839511232906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PDZ15gaiYJZLQ7J4YJxPGwsoXFBJEphgvoBX7JYihHE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXKIBMCVJSWA62PHGB5AO33U366O3ANCNFSM5OWICNRQ&data=04%7C01%7C%7C504913588ce946da1dcb08d9f3c2a102%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637808839511232906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Gfo%2BOACVqQtXzJUMeMN52yA%2B7Nl2ui5QsVkt7H%2FZy7g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C504913588ce946da1dcb08d9f3c2a102%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637808839511232906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S9CYLkUe7l%2B6C%2BrrDmqTLCuRZIntdsbdk4kkxFFRI%2B8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C504913588ce946da1dcb08d9f3c2a102%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637808839511232906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ysdHiUcOz3Y05CxcszvSMps%2FfHcJBBWWf%2BP3D9CKoDA%3D&reserved=0>.

**Pull request closed without merging**
