### PR TITLE
Add first KEKW NFT

### PR DESCRIPTION
**Pull request by kekwcoin**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: 5WUab7TCvth43Au5vk6wKjchTzWFeyPEUSJE1MPJtTZE
* Token Name: KEKW In Solana Tripping
* Token Symbol: KEKN1
* Logo: https://www.kekw.io/images/KEKN1_logo.png
* Link to the official homepage of token: https://www.kekw.io/

### CODE REVIEW

**Review by kekwcoin — COMMENTED** [review]
updated token address

**Review by kekwcoin — COMMENTED** [review]
adjust decimals

**Review by kekwcoin — COMMENTED** [review]
fixed

**Review by kekwcoin — COMMENTED** [review]
added nft tag

**Comment by oJshua** [comment]
https://github.com/solana-labs/token-list/pull/216

**Pull request closed without merging**
