### PR TITLE
Added oDop to tokenlist

### PR DESCRIPTION
**Pull request by cesar128**
oDop is a stable-coin based on Dominican Peso.

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
Can you add more details about the project and maybe link to the whitepaper and logo?

**Comment by Dante2333** [comment]
Odop.io is the site

oDOP idea is to be the stablecoin of Dominican peso that bridges the Dominican economy with the Serum / Solana ecosystem. We're currently on bonfida and soon will launch our own bitcoin/odop and eth/odop markets on bonfida. 

The oDOP cryptocurrency works with a single entity OuroSRL which is the sole minter of the oDOP token. Traders that mint/redeem oDOP are subject to KYC/AML checks and only after having passing those then they can purchase or redeem the oDOP token. Sales of oDOP for fiat currencies only occur in the Dominican Republic.

**Comment by bartosz-lipinski** [comment]
Awesome can you update website to point to: Odop.io instead of https://ourord.com/, resolve conflicts and add token logo.

**Comment by gregpozo** [comment]
oDOP
oDOP image

**Comment by gregpozo** [comment]
> Awesome can you update website to point to: Odop.io instead of https://ourord.com/, resolve conflicts and add token logo
please let me know if this works for you

**Pull request closed without merging**
