### PR TITLE
Add CRC Token

### PR DESCRIPTION
**Pull request by carecointoken**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR

At minimum each entry should have
* Token Address: z9WZXekbCtwoxyfAwEJn1euXybvqLzPVv3NDzJzkq7C
* Token Name: Care Coin Token
* Token Symbol: CRC
* Logo: https://i.postimg.cc/VLHNbwv5/1624369860-icon.png
* Link to the official homepage of token: https://www.carecoin.site/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
Please add website

**Comment by carecointoken** [comment]
we already add the website, please check it

**Comment by carecointoken** [comment]
that any details we must put it again?

**Comment by carecointoken** [comment]
@bartosz-lipinski @oJshua 🙏

**Comment by carecointoken** [comment]
> Please add website

  @bartosz-lipinski

**Comment by carecointoken** [comment]
@bartosz-lipinski @mvines can you check on us?? already waiting 9 days now, if any mistake lets us know

**Comment by carecointoken** [comment]
@oJshua @chaseeb please and thanks for your time

**Comment by bartosz-lipinski** [comment]
Please don’t modify other tokens

**Comment by carecointoken** [comment]
need we closed this and make the new one? @bartosz-lipinski @mvines ?

**Pull request closed without merging**
