### PR TITLE
Change coin logo

### PR DESCRIPTION
**Pull request by oboxodo**
This is an update to one of our own tokens.

### CODE REVIEW

**Comment by oboxodo** [comment]
Hi @keone. Do you think it'd be possible to merge this logo update? :pray:

**Comment by keone** [comment]
added in https://github.com/solana-labs/token-list/commit/fb09a6b2113b42aca4c2f51b9f02b91becc091b8

**Comment by keone** [comment]
merged! please raise an issue in the future, so that all of the maintainers are alerted to your need

**Comment by oboxodo** [comment]
Thank you! Will do.

**Pull request merged**
