### PR TITLE
add simoleon website

### PR DESCRIPTION
**Pull request by alex-dp**

### CODE REVIEW

**Comment by alex-dp** [comment]
I don't understand this error. can someone help?

**Comment by oboxodo** [comment]
Sorry, I'm a plain contributor just like you who can't merge PRs. I have my own correction PRs waiting forever too.

**Comment by alex-dp** [comment]
> Sorry, I'm a plain contributor just like you who can't merge PRs.

sorry I tagged random people. do you know who I could tag?

**Comment by keone** [comment]
https://github.com/solana-labs/token-list/commit/61f5f8b700316c27746646d2343f9ac567b05ab5

**Comment by oboxodo** [comment]
Wow! your prayers have been heard!

Hey @keone do you think you could merge my 2 open PRs modifying my own tokens?
1. https://github.com/solana-labs/token-list/pull/5159
2. https://github.com/solana-labs/token-list/pull/4993

**Pull request merged**
