### PR TITLE
adding token for DICK & Dickcoin

### PR DESCRIPTION
**Pull request by inksolum**
## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by Ron8d** [comment]
would you be so kind as to let me know how you are dealing with the no newline added showing as a deletion in your json file?   I've been trying for two days and no one will explain it, I cannot find an answer and am really struggling.  Sorry to bother you if it is too much for you to address.  Thanks.

**Comment by inksolum** [comment]
Hi,

Not sure to be honest. I've tried like 7 times. Had the same issue as you.
I've just copied and pasted right after one of the other tokens. Then saved
without trying to format the json file and it worked. Probably was
struggling before because was worrying too much about the formatting.

**Comment by Ron8d** [comment]
did you use the editor in github or somewhere else?

**Comment by inksolum** [comment]
No, I used notepad++

**Pull request merged**
