### PR TITLE
change MoppelCoin logoURI

### PR DESCRIPTION
**Pull request by fleibfried**
## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

I MADE A MISTAKE WHEN PROVIDING THE MOPPELCOIN LOGO URI. NOW I WANT TO CHANGE IT BY PROVIDING THE CORRECT LOGO URI. PLEASE APPROVE THE MERGE!!!

- Token Address: E5H5mHzUA8pRSL4X2ovv4sZMSorYk56EtCbQExQveRGJ
- Token Name: MoppelCoin
- Token Symbol: MPPLC
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/E5H5mHzUA8pRSL4X2ovv4sZMSorYk56EtCbQExQveRGJ/logo.png
- Link to the official homepage of token: https://sites.google.com/view/moppelcoin/startseite
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by fleibfried** [comment]
Please not that i have also updated the logo file itself to be 100x100 pixels.

**Comment by keone** [comment]
Please rebase onto main

**Comment by fleibfried** [comment]
> Please rebase onto main

Thanks @keone , I have updated my branch. Please let me know if there are anymore issues.

**Comment by keone** [comment]
merged

**Pull request merged**
