### PR TITLE
New Id hopefully this will fix it - Please comment anyone knows what I am doing wrong - Reducing size of image 1st

### PR DESCRIPTION
**Pull request by Grit-Dev**
---
# Please note: This repository is being rebuilt to accept the new volume of token additions and modifications. PR merges will be delayed.
---

## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

## Auto merge requirements

Your pull request will be automatically merged if the following conditions are met:

- Your pull request **only adds new tokens** to the list. Any modification to existing
  tokens will require manual review to prevent unwanted modifications.

- Your pull request does **not touch unrelated code**. In particular, reformatting changes to unrelated
  code will cause the auto merge to reject your PR.

- Any **asset files added correspond to the token address** you are adding. Asset files
  must be PNG, JPG or SVG files.

- Your change is **valid JSON** and **conforms to the schema**. If your change failed validation,
  read the error message carefully and update your PR accordingly.

- No other tokens shares the **same name, symbol or address**.

For example, this change would be rejected due to unrelated changes:

The bot runs **every 60 minutes** and bulk-merges all open pull requests to prevent conflicts.
This means that you need to wait up to 60 minutes for your pull request to be merged or reprocessed.

### CODE REVIEW

**Comment by Zues369** [comment]
The reason also for last one error was " "logoURI": "https://github.com/Grit-Dev/crypto1/blob/main/TryTwo.png", " you used the blob instead of the main pic that one would work now

**Comment by Grit-Dev** [comment]
> The reason also for last one error was " "logoURI": "https://github.com/Grit-Dev/crypto1/blob/main/TryTwo.png", " you used the blob instead of the main pic that one would work now
> 
> "logoURI": "https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png", is good and if still error try remane to logo, but that would work now

What is the blob, and how do you change it to the main then if that makes sense? I have limited experience so this is stilll pretty new to me. 

I cannot seem to be allowed to rename it too: assets/mainnet/DU1uTzkfAMWYhPs5GdprFYmGSMcEFZvX4ScbpBxkBdDf/logo for some reason.

**Comment by Zues369** [comment]
yeah no worries the only thing you got to edit is the logourl just replace it with this and it will be fine 

      "logoURI":"https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png",

**Comment by Grit-Dev** [comment]
> yeah no worries the only thing you got to edit is the logourl just replace it with this and it will be fine
> 
> ```
>   "logoURI":"https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png",
> ```

Perfect bro! If this fails again, I will just add that link to it! Thanks again, really appreciate this as I have been at this all weekend as a experiment to get this done! Really appreciate it!!!!!!

**Comment by Zues369** [comment]
yeah and if the image doesn't go thru try to use this line 

"logoURI":" https://raw.githubusercontent.com/Zues369/SWERV-logo/main/logo.png",

**Comment by Zues369** [comment]
> > yeah no worries the only thing you got to edit is the logourl just replace it with this and it will be fine
> > ```
> >   "logoURI":"https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png",
> > ```
> 
> Perfect bro! If this fails again, I will just add that link to it! Thanks again, really appreciate this as I have been at this all weekend as a experiment to get this done! Really appreciate it!!!!!!

sure you are most welcome and yeah I had a similar error in the past so got the hang of it by now here and there

**Comment by Grit-Dev** [comment]
> > > yeah no worries the only thing you got to edit is the logourl just replace it with this and it will be fine
> > > ```
> > >   "logoURI":"https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png",
> > > ```
> > 
> > 
> > Perfect bro! If this fails again, I will just add that link to it! Thanks again, really appreciate this as I have been at this all weekend as a experiment to get this done! Really appreciate it!!!!!!
> 
> sure you are most welcome and yeah I had a similar error in the past so got the hang of it by now here and there

Thank you again, it can be frustrating spending hours and hours trying all these things, to figure out it is something simple. Always the way haha. I do appreciate it! I do hope it merges now so no more changes, but if not, I hope that line works.

I just want this one coin in the bag for fun

**Comment by Grit-Dev** [comment]
> > > yeah no worries the only thing you got to edit is the logourl just replace it with this and it will be fine
> > > ```
> > >   "logoURI":"https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png",
> > > ```
> > 
> > 
> > Perfect bro! If this fails again, I will just add that link to it! Thanks again, really appreciate this as I have been at this all weekend as a experiment to get this done! Really appreciate it!!!!!!
> 
> sure you are most welcome and yeah I had a similar error in the past so got the hang of it by now here and there

It says this has automerged!!!!!!!!!!!! Does that mean it has actually passed!!!

**Comment by Zues369** [comment]
> > > > yeah no worries the only thing you got to edit is the logourl just replace it with this and it will be fine
> > > > ```
> > > >   "logoURI":"https://raw.githubusercontent.com/Grit-Dev/crypto1/main/TryTwo(1).png",
> > > > ```
> > > 
> > > 
> > > Perfect bro! If this fails again, I will just add that link to it! Thanks again, really appreciate this as I have been at this all weekend as a experiment to get this done! Really appreciate it!!!!!!
> > 
> > 
> > sure you are most welcome and yeah I had a similar error in the past so got the hang of it by now here and there
> 
> It says this has automerged!!!!!!!!!!!! Does that mean it has actually passed!!!

Hey Congrats all the best on your New Token

**Comment by Grit-Dev** [comment]
Adding Token ID - Think I used token wallet instead of the ID

**Pull request closed without merging**
