### PR TITLE
refactor: remove SolaPAD Token duplicate

### PR DESCRIPTION
**Pull request by beautyfree**
Remove duplicate from https://github.com/solana-labs/token-list/pull/173 causes "key" errors in React

### CODE REVIEW

**Comment by beautyfree** [comment]
Fix mistakes in https://github.com/solana-labs/token-list/pull/173

**Comment by beautyfree** [comment]
@bartosz-lipinski check please

**Comment by aaronovz1** [comment]
Getting the same React errors. @oJshua can we get this one merged, please and thank you.

**Comment by oJshua** [comment]
Sorry for the delay on this @beautyfree @aaronovz1. We can add a check for duplicate keys. I'll create a ticket.

**Comment by anishmenon** [comment]
@oJshua  Why it's taking too long for approval if there are any comments we can modify. PR : https://github.com/solana-labs/token-list/pull/317

**Pull request merged**
