### PR TITLE
feat: add step token

### PR DESCRIPTION
**Pull request by step-finance**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT
* Token Name: Step
* Token Symbol: STEP
* Logo: https://cdn.jsdelivr.net/gh/solana-labs/token-list/assets/mainnet/StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT/logo.jpg
* Link to the official homepage of token: https://step.finance

### CODE REVIEW

**Comment by step-finance** [comment]
@oJshua Is there anything we need to do to get the logo on the cdn? I thought adding it to the assets would work. Does something need to deployed?

**Comment by oJshua** [comment]
@step-finance hmm, was noticing that image didn't resolve for me last night. Let me see what I can do.

**Comment by oJshua** [comment]
Stand by, https://github.com/solana-labs/token-list/pull/64

**Comment by step-finance** [comment]
> Stand by, #64

Ah my bad! Thanks!

**Comment by oJshua** [comment]
@step-finance Not a problem! Cheers!

**Pull request merged**
