### PR TITLE
Add DriftCoin logo and Data

### PR DESCRIPTION
**Pull request by rigwars**
At minimum each entry should have

- Token Address: ChvvzHyRqCHnLVwMNz8amvQwgVLD8AELV7RgcFAxEhAf
- Token Name: DriftCoin
- Token Symbol: DRIFT
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ChvvzHyRqCHnLVwMNz8amvQwgVLD8AELV7RgcFAxEhAf/logo.png
- Link to the official homepage of token: https://driftcoin.org

### CODE REVIEW

**Comment by Shipon76** [comment]
6dX7ceRy4rhWBuAUarsKZb3rFcGYkVJYWnmvcnaRM6UU

**Comment by Amumeen** [comment]
8K19mSLZZZwp6tvx1dHgSQ6jS4CjwZLyQr7cXxwYeRL1

**Comment by cuke746** [comment]
5cQE7JgpFNpNWwMehwEbMadM8nBse8x7mRQzSPRubgRJ

**Comment by longchen555** [comment]
3rXFcvmSr7e1hGAv4shCo7ZG1MtthK9K5JrVwuxiayP7

**Comment by Milestheman27** [comment]
0x6Ba59B383D2F68963B48C7cb008BADC89B0f7563

**Comment by Milestheman27** [comment]
3Hta1s5sY26pSPAhVvQUJXFeA7XbppyGf8yLz1dmcN4Z

**Comment by omarqt02** [comment]
HxLHnd4NMTwZNuAaptNB5c8A2zPwaQbsFvKhohpRHVE1

**Comment by rigwars** [comment]
Guys, please it is not an airdrop request channel :)

**Pull request merged**
