### PR TITLE
Update icon for KISSES coin

### PR DESCRIPTION
**Pull request by kisscoins**
---
# Please note: This repository is being rebuilt to accept the new volume of token additions and modifications. PR merges will be delayed.
---

## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

## Auto merge requirements

Your pull request will be automatically merged if the following conditions are met:

- Your pull request **only adds new tokens** to the list. Any modification to existing
  tokens will require manual review to prevent unwanted modifications.

- Your pull request does **not touch unrelated code**. In particular, reformatting changes to unrelated
  code will cause the auto merge to reject your PR.

- Any **asset files added correspond to the token address** you are adding. Asset files
  must be PNG, JPG or SVG files.

- Your change is **valid JSON** and **conforms to the schema**. If your change failed validation,
  read the error message carefully and update your PR accordingly.

- No other tokens shares the **same name, symbol or address**.

For example, this change would be rejected due to unrelated changes:

The bot runs **every 60 minutes** and bulk-merges all open pull requests to prevent conflicts.
This means that you need to wait up to 60 minutes for your pull request to be merged or reprocessed.

### CODE REVIEW

**Comment by kisscoins** [comment]
Hello, i tried to update the logo for my token but it seems that it needs a manual review, can you please check it? thank you

**Comment by keone** [comment]
this adds another block instead of editing the existing one, see https://github.com/solana-labs/token-list/pull/11247/files

**Comment by kisscoins** [comment]
> this adds another block instead of editing the existing one, see https://github.com/solana-labs/token-list/pull/11247/files

Thank you @keone i'm new to github, i created a PR updating the logo file but the automerger rejected the changes cause it marked as a duplicated token. Should i change the image url for manual review? i think this is a little more complicated for me because i need to delete my current fork and fork it again, i was unable to sync the new influx of PRs.

Btw i learned about warmhole wrapped tokens and bridged from AVAX to SOLANA thanks to a commit of yours.

**Comment by keone** [comment]
i think you need to make a commit with ONLY the logo changed, no json change.  if i were you i'd just push onto this branch another commit that reverts the change to the json.

**Comment by kisscoins** [comment]
> i think you need to make a commit with ONLY the logo changed, no json change. if i were you i'd just push onto this branch another commit that reverts the change to the json.

Thank your @keone im not sure how to do that but i will try

**Comment by kisscoins** [comment]
> i think you need to make a commit with ONLY the logo changed, no json change. if i were you i'd just push onto this branch another commit that reverts the change to the json.

I think i made the changes you suggested, it still needs manual revision for the logo update commit right?

**Comment by keone** [comment]
looks good

token originally added in https://github.com/solana-labs/token-list/commit/1d68d18efa1730fadad62bedc28e1eca4f8e28fe

**Comment by keone** [comment]
conflicts made it difficult to merge this directly, so did so in #11371

**Pull request closed without merging**
