### PR TITLE
Add SolStar token.

### PR DESCRIPTION
**Pull request by ryan-endacott**
- [x] I will not ping the Discord about this pull request.

Hello Solana team!  I hope you're all doing well :) we've created our [mainnet token](https://explorer.solana.com/address/D7U3BPHr5JBbFmPTaVNpmEKGBPFdQS3udijyte1QtuLk) for SolStar. Please see below and the attached PR. Thanks!

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR

At minimum each entry should have
* Token Address:  Done.
* Token Name:  Done.
* Token Symbol:  Done.
* Logo:  Done.
* Link to the official homepage of token: Done. 
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):  Not yet applicable.

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
please store logo in this repo under assets/mainnet/<mint>

**Comment by ryan-endacott** [comment]
Hey Bartosz, thanks!  Uploaded our image to the assets folder and changed our image link to point to it.  Let me know if there's anything else we need to do to get this merged.

**Comment by ryan-endacott** [comment]
Thank you so much Bartosz!

**Comment by mlilvic** [comment]
Very good 👍

**Pull request merged**
