### PR TITLE
Disable automerge; label preserved

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Turn off merge part of automerge workflow

### CODE REVIEW

**Comment by CoinHunterFiverr** [comment]
when enable automerge ?

**Comment by Learning420** [comment]
hello, when will this feature be re enabled?

**Comment by Learning420** [comment]
or is this permanent?

**Comment by oboxodo** [comment]
https://github.com/solana-labs/token-list/pull/4350 :pray:

**Comment by CoinHunterFiverr** [comment]
Merge this #4350

**Comment by CoinHunterFiverr** [comment]
Merge this #4350 @CriesofCarrots

**Pull request merged**
