### PR TITLE
Add WOOF Token

### PR DESCRIPTION
**Pull request by solroamer**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: 9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE
* Token Name: WOOFENOMICS
* Token Symbol: WOOF
* Logo: https://i.ibb.co/sHb9qZj/woof-orange-black.png
* Link to the official homepage of token: https://www.woofsolana.com/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
can you update link to image to point to image not website

**Comment by solroamer** [comment]
> can you update link to image to point to image not website

Updated

**Comment by solroamer** [comment]
> > > can you update link to image to point to image not website
> > 
> > 
> > Updated
> 
> Link in PR is still pointing to non-image uri

Updated, 
Should not rush and do it slowly and correctly instead. Thanks.

**Comment by izayoido** [comment]
Can I change the logo and the name?

**Pull request merged**
