### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by DenizenK**
---
# Please note: This repository is being rebuilt to accept the new volume of token additions and modifications. PR merges will be delayed.
---

## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

## Auto merge requirements

Your pull request will be automatically merged if the following conditions are met:

- Your pull request **only adds new tokens** to the list. Any modification to existing
  tokens will require manual review to prevent unwanted modifications.

- Your pull request does **not touch unrelated code**. In particular, reformatting changes to unrelated
  code will cause the auto merge to reject your PR.

- Any **asset files added correspond to the token address** you are adding. Asset files
  must be PNG, JPG or SVG files.

- Your change is **valid JSON** and **conforms to the schema**. If your change failed validation,
  read the error message carefully and update your PR accordingly.

- No other tokens shares the **same name, symbol or address**.

For example, this change would be rejected due to unrelated changes:

The bot runs **every 60 minutes** and bulk-merges all open pull requests to prevent conflicts.
This means that you need to wait up to 60 minutes for your pull request to be merged or reprocessed.

### CODE REVIEW

**Comment by testsystemca** [comment]
I have same issue ,
Do you have any idea how to fix it ?

**Comment by DenizenK** [comment]
No, and can't find anything online. Going to add question to issues

**Comment by denizTutuncu** [comment]
I am also having the same issue.

**Comment by testsystemca** [comment]
https://github.com/solana-labs/token-list/pull/11247#issuecomment-1002735975

I found this but didn't work for me

**Comment by denizTutuncu** [comment]
So we need to commit the logo first without json changes then add the json and commit again. Thx for the comment. I'll give it a try and let you guys know.

**Comment by testsystemca** [comment]
> So we need to commit the logo first without json changes then add the json and commit again. Thx for the comment. I'll give it a try and let you guys know.

Do not have idea how to do 
Please let me know if it works for you

**Comment by keone** [comment]
added in https://github.com/solana-labs/token-list/commit/c9b052ba03a735bb6558837e1af75402736972f3

**Comment by denizTutuncu** [comment]
> > So we need to commit the logo first without json changes then add the json and commit again. Thx for the comment. I'll give it a try and let you guys know.
> 
> Do not have idea how to do Please let me know if it works for you

Hey @testsystemca,

I believe I find the issue. When you fork the project, go to its directory and install the packages via `npm install @solana/spl-token-registry` then make your changes like add your token in the JSON array and create a folder then called it with your token address. Add the token logo png inside that folder then move that folder into token-list/assets/mainnet. On this point you can commit your changes and push it. Open a PR. I believe it should work.

**Comment by denizTutuncu** [comment]
> > > So we need to commit the logo first without json changes then add the json and commit again. Thx for the comment. I'll give it a try and let you guys know.
> > 
> > 
> > Do not have idea how to do Please let me know if it works for you
> 
> Hey @testsystemca,
> 
> I believe I found the issue. It's actually my mistake to not install the packages. When you fork the project, go to its directory and install the packages via `npm install @solana/spl-token-registry` then make your changes like add your token in the JSON array and create a folder then called it with your token address. Add the token logo png inside that folder then move that folder into token-list/assets/mainnet. On this point you can commit your changes and push it. Open a PR. I believe it should work.

**Comment by testsystemca** [comment]
> > > So we need to commit the logo first without json changes then add the json and commit again. Thx for the comment. I'll give it a try and let you guys know.
> > 
> > 
> > Do not have idea how to do Please let me know if it works for you
> 
> Hey @testsystemca,
> 
> I believe I find the issue. When you fork the project, go to its directory and install the packages via `npm install @solana/spl-token-registry` then make your changes like add your token in the JSON array and create a folder then called it with your token address. Add the token logo png inside that folder then move that folder into token-list/assets/mainnet. On this point you can commit your changes and push it. Open a PR. I believe it should work.

Hm I confuse,  where should I run    npm install @solana/spl-token-registry  this  code , could you please send me screenshot if you have it

**Comment by denizTutuncu** [comment]
> > > > So we need to commit the logo first without json changes then add the json and commit again. Thx for the comment. I'll give it a try and let you guys know.
> > > 
> > > 
> > > Do not have idea how to do Please let me know if it works for you
> > 
> > 
> > Hey @testsystemca,
> > I believe I find the issue. When you fork the project, go to its directory and install the packages via `npm install @solana/spl-token-registry` then make your changes like add your token in the JSON array and create a folder then called it with your token address. Add the token logo png inside that folder then move that folder into token-list/assets/mainnet. On this point you can commit your changes and push it. Open a PR. I believe it should work.
> 
> Hm I confuse, where should I run npm install @solana/spl-token-registry this code , could you please send me screenshot if you have it

You can run that piece of code on your terminal. Open your terminal, cd directory where you clone the project. Mine is on Desktop/SOLTokenList/token-list. You will have different path than mine. Then you can run the code. 

Screen Shot 2021-12-30 at 2 23 20 PM

**Pull request merged**
