### PR TITLE
Added Kreechure NFTs

### PR DESCRIPTION
**Pull request by m4thfr34k**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: 
* Token Name: 
* Token Symbol: 
* Logo
* Link to the official homepage of token:
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by chriskalani** [comment]
@bartosz-lipinski can we get this merged in so Kreechure's show up in Phantom properly? Thanks!

**Comment by m4thfr34k** [comment]
Are these PRs reviewed on some schedule that can be published to set expectations? This particular PR was submitted 16-days ago and contains the NFT details on all current Kreechures. Players/Users are excited to be able to see their Solana NFT, Kreechure, in their wallets, like Phantom wallet, but are unable to until this PR is merged.

**Comment by fragosti** [comment]
This PR needs to be re-done because the diff is too large to review. Did you lint it or something? There should be a linter command you can run to un-do it.

**Comment by m4thfr34k** [comment]
I can break the PR up into multiple, smaller, submissions; however, it's
not too larger due to a linter. This PR includes nearly 2000 Kreechure NFTs
like the 2 that already exist on the token list. The file can be downloaded
to review if not viewable in browser.

**Comment by fragosti** [comment]
Uff. Maybe its better if you go directly to the Metadata standard https://www.notion.so/Metadata-064594b7d7df4468a4993b161c9a2719

**Comment by m4thfr34k** [comment]
I can for future Kreechures; however, these have already been
created/minted and for most of them, provided to players/users and sent to
their wallets. I have already created a PR for two Kreechures which was
previously reviewed and approved. I submitted these based on that
successful test.

Not sure if the new standard would allow me to add that metadata on
existing NFTs.

**Comment by bartosz-lipinski** [comment]
> Uff. Maybe its better if you go directly to the Metadata standard https://www.notion.so/Metadata-064594b7d7df4468a4993b161c9a2719

I agree json list should not be used here. 2000 items is way too many. Please creates metadata on-chain: https://www.notion.so/Metadata-064594b7d7df4468a4993b161c9a2719

**Comment by m4thfr34k** [comment]
Roger that.

**Pull request closed without merging**
