### PR TITLE
Adding JEBUS token

### PR DESCRIPTION
**Pull request by r4881t**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: 5jqTNKonR9ZZvbmX9JHwcPSEg6deTyNKR7PxQ9ZPdd2w
* Token Name: JEBUS
* Token Symbol: JBUS
* Logo
* Link to the official homepage of token:
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by oJshua** [comment]
Please add a website and logo! Thanks.

**Comment by SaujanaOK** [comment]
We are waiting your progress, Please add a website and twitter community.

**Comment by r4881t** [comment]
The team is on it. It will take some time before it happens. Should I close this PR and re open later?

**Comment by r4881t** [comment]
Updated with (a) logo and (b) website

**Pull request merged**
