### PR TITLE
Update solana.tokenlist.json

### PR DESCRIPTION
**Pull request by solanasail**
- [ ] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: 6kwTqmdQkJd8qRr9RjSnUX9XJ24RmJRSrU1rsragP97Y
* Token Name: SAIL
* Token Symbol:  : SAIL
* Logo : https://cloudflare-ipfs.com/ipfs/QmPcQfofQNfiv36EAsGQrgAhiPbqGf17i1Cz648JhXFW9m/logo_solana_sail_v2.png
* Link to the official homepage of token: https://www.solanasail.com
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by solanasail** [comment]
When will you approve my PR ? I'm still waiting for my project, thanks @oJshua

**Comment by oJshua** [comment]
@solanasail This branch just needs to resolve conflicts first. Could you rebase or merge with latest?

**Comment by solanasail** [comment]
Thanks @oJshua , conflicts are resolved now.

**Comment by oJshua** [comment]
@solanasail Sorry to be a pain, but could you undo commits f9dfaad and 5610ee5 that created releases? We just need the token list JSON updated. Feel free to force push to your branch.

**Comment by solanasail** [comment]
no problem @oJshua , I will close this PR and create a new one with only the token list JSON file. Hope that my new PR will not be queued ;-)

**Pull request closed without merging**
