### PR TITLE
CARE COIN

### PR DESCRIPTION
**Pull request by carecointoken**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR

At minimum each entry should have
* Token Address: z9WZXekbCtwoxyfAwEJn1euXybvqLzPVv3NDzJzkq7C
* Token Name: Care Coin Token
* Token Symbol: CRC
* Logo  https://i.postimg.cc/VLHNbwv5/1624369860-icon.png
* Link to the official homepage of token: https://www.carecoin.site
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
please store logo in this repo under assets/mainnet/<mint>

**Comment by carecointoken** [comment]
done @bartosz-lipinski

**Comment by carecointoken** [comment]
eror? can we know how to fix it? we new on solana, hope lets us know so we can fix it, thanks alot if you help us

**Comment by carecointoken** [comment]
@bartosz-lipinski  @mvines need your help, we already fix it, can you run test again? sorry for tag

**Comment by carecointoken** [comment]
@bartosz-lipinski  @mvines , need your help to check it again sir

**Pull request merged**
