### PR TITLE
Add MoonLana Token

### PR DESCRIPTION
**Pull request by Moonlana**
- [ ] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: AMdnw9H5DFtQwZowVFr4kUgSXJzLokKSinvgGiUoLSps
* Token Name: MoonLana
* Token Symbol: MOLA
* Logo: https://i.ibb.co/NtrSyDc/moonlana.jpg
* Link to the official homepage of token: https://moonlana.com/

### CODE REVIEW

**Comment by Moonlana** [comment]
@garious hello, when could this change be integrated into the main branch?

**Comment by Moonlana** [comment]
@bartosz-lipinski hello, when could this change be integrated into the main branch?

**Comment by Moonlana** [comment]
Guys, Excuse me, but when can the request be evaluated? @garious @dmakarov @ryoqun @Reisen

**Comment by im354** [comment]
Nyimak

**Comment by NGepetSun** [comment]
Go Go Goo

**Comment by iqbalmahendraaa** [comment]
MoonLana go to the mars

**Comment by fizzar99** [comment]
Letso molaa. We can dl it😎😍

**Pull request merged**
