### PR TITLE
Commit17 BX Bitphoenix X

### PR DESCRIPTION
**Pull request by bitphoenixx**
## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by bitphoenixx** [comment]
It is mergeable but why does not merge to main net on solona

**Comment by bitphoenixx** [comment]
Hallo Sir I am wating for PR merge 
Please merge it , why it shows automerge but does not work actully for me

**Comment by bitphoenixx** [comment]
**

this the last commit to Update BX Bitphoenix X.

**
thank you

**Comment by bitphoenixx** [comment]
> this is he last commit to Update BX **Bitphoenix** X.

**
thank you

**Comment by Solana-Developer** [comment]
Please read the [SPL-token README](https://github.com/SolDev-stack/token-list/blob/main/README.md), and ensure your SPL-token info uses the correct [Uniswap format](https://github.com/SolDev-stack/token-lists/blob/main/README.md).

**Comment by bitphoenixx** [comment]
i try for days why it does not merge what is the problem 
Please help someone

**Comment by bitphoenixx** [comment]
i need your help , how should i merge it ?!!!!

**Comment by bitphoenixx** [comment]
a little change

**Comment by bitphoenixx** [comment]
it

**Comment by bitphoenixx** [comment]
please approve as soon as posbl.
thank you

**Comment by bitphoenixx** [comment]
if this time does not work , cann i completly delete the token-list and start from Beginn to merge

**Comment by bitphoenixx** [comment]
what is the problem this time: the error shows > unsupported file modified: .github/PULL_REQUEST_TEMPLATE.md
i have not changed it

**Pull request closed without merging**
