### PR TITLE
Added tags and official website

### PR DESCRIPTION
**Pull request by chptokenadmin**
---
# Please note: This repository is being rebuilt to accept the new volume of token additions and modifications. PR merges will be delayed.
---

## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR.
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address:
- Token Name:
- Token Symbol:
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>)
- Link to the official homepage of token:
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

## Auto merge requirements

Your pull request will be automatically merged if the following conditions are met:

- Your pull request **only adds new tokens** to the list. Any modification to existing
  tokens will require manual review to prevent unwanted modifications.

- Your pull request does **not touch unrelated code**. In particular, reformatting changes to unrelated
  code will cause the auto merge to reject your PR.

- Any **asset files added correspond to the token address** you are adding. Asset files
  must be PNG, JPG or SVG files.

- Your change is **valid JSON** and **conforms to the schema**. If your change failed validation,
  read the error message carefully and update your PR accordingly.

- No other tokens shares the **same name, symbol or address**.

For example, this change would be rejected due to unrelated changes:

The bot runs **every 60 minutes** and bulk-merges all open pull requests to prevent conflicts.
This means that you need to wait up to 60 minutes for your pull request to be merged or reprocessed.

### CODE REVIEW

**Comment by chptokenadmin** [comment]
@keone kindly merge these changes manually if possible. Thanks!

**Comment by keone** [comment]
you need to edit the existing block; this diff re-adds a duplicate, see: https://github.com/solana-labs/token-list/pull/8506/files

**Comment by chptokenadmin** [comment]
Hi @keone , below are the codes when this was initially submitted:
    {
      "chainId": 101,
      "address": "DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn",
      "symbol": "CHP",
      "name": "Crypto Health Plus",
      "decimals": 9,
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn/logo.png"
	 },

Then it got accepted by the repository. And then we decided adding the official websites/social media links with these codes:
    {
      "chainId": 101,
      "address": "DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn",
      "symbol": "CHP",
      "name": "Crypto Health Plus",
      "decimals": 9,
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn/logo.png",
      "tags": [
        "health"
      ],
      "extensions": {
        "facebook": "https://www.facebook.com/Crypto-Health-Plus-226283872703673/",
        "twitter": "https://twitter.com/CryptoHealthPls",
        "website": "https://cryptohealthplus.com/"
      }
	 },

The initial code that got accepted by auto-merger do not have the "," (comma) after the "logo.png". This may be the one giving us the hard stop that is not allowing us to edit the codes without the system detecting it as deletion or adding another logoURI line.

Kindly enlighten us. Thanks!

**Comment by chptokenadmin** [comment]
Keone,

Hello and thank you for your email. I do not understand what this means: you need to edit the existing block; this diff re-adds a duplicate, see: https://github.com/solana-labs/token-list/pull/8506/files Can you please break it down to me in step by step to what I need to do to fix this problem so we can both go about our day and stop waiting precious time going back and forth. I really appreciate your help in this matter. Thanks again,

Best Regards,

Michael Coscarelli
832-435-1505
***@***.***
www.cryptohealthplus.com<http://www.cryptohealthplus.com>
[https://img1.wsimg.com/isteam/stock/xVdmO8j]<http://www.cryptohealthplus.com/>
Living Your Best Life<http://www.cryptohealthplus.com/>
Get started on the path to healthcare in your own hands!
www.cryptohealthplus.com



________________________________

**Comment by keone** [comment]
search for `DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn` in the unedited version of the json file.  you will find this block:

```
    {
      "chainId": 101,
      "address": "DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn",
      "symbol": "CHP",
      "name": "Crypto Health Plus",
      "decimals": 9,
      "logoURI": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/DHVUoxNqv3D7EgktBxUsxFF2Wx83hVDmD2wBBpUaw3jn/logo.png"
    },
```

edit that

**Review by chptokenadmin — COMMENTED** [review]
We are still having issues with getting this fixed. It is needed for a dev to manually modified it so our website will be verified. Look at the screen shot below that shows our website is verified. I really appreciate your help in this matter as we have been working on this for over a month now. Thank you,

**Comment by chptokenadmin** [comment]
CHP Website Verifcation

**Comment by keone** [comment]
i think my instructions were clear, please ask a friend to read my instructions and see if they make more sense to them.  your diff is clearly adding a new block instead of editing the existing one: https://github.com/solana-labs/token-list/pull/8506/files

**Comment by chptokenadmin** [comment]
Closing ticket as this has https://github.com/solana-labs/token-list/pull/17821

**Pull request closed without merging**
