### PR TITLE
Update all logoURI using repository's internal link

### PR DESCRIPTION
**Pull request by bigearsenal**
- [x] I will not ping the Discord about this pull request.

I have downloaded all the logos that are downloadable and saved into this repository in `assets/mainnet/<token_address>`, so we can use internal logos' links that refers to this repository.
Format of logo images will be: `https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/<token_address>/logo.<svg || png>`

solana.tokenlist.json has been updated accordingly:
`
...
logoURI: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ASwYCbLedk85mRdPnkzrUXbbYbwe26m71af9rzrhC2Qz/logo.svg",
...
`
And from now one, I suggested that anyone who is gonna add token should follow the rules by download their logo, add it to `assets/mainnet/<token_address>/logo.<svg || png>` for better references.

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
This is awesome can you add unitest that verifies if logo has been added to the repository as well

**Comment by bigearsenal** [comment]
I think we should separate the json file.
Each newly added tokens now has its own folder, the folder is now required to have `logo.png` and `info.json`.
The file `solana.tokens.json` should now be generated automatically by combining all the `info.json` files in assets folder.

**Comment by Seigneur-Machiavel** [comment]
Thank you for clarity, but we can't add folder/file (i have prepare both to add LP-token logo)
So how can we do it please ?

**Comment by TokenNetworkSecurity** [comment]
I updated the repository by preloading the token logo. But the token is never added to the token sheet. Who can help me with this?

**Pull request merged**
