### PR TITLE
added metabook token with logos

### PR DESCRIPTION
**Pull request by AyoCodess**
## I agree to not ping _anybody_ on Discord/Twitter/email about this pull request. Instead I will inquire by posting a new comment in the pull request if needed.

---

PRs are reviewed in bulk and and can take up to **two weeks** to be merged.

_This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged._

## **Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR. - YES, DONE
DON'T modify any other token on the list.

At minimum each entry should have

- Token Address: D73ZAaGZnsvM4gJUTJ1BfKkPH8zmyv5om97vfwu4MTkD
- Token Name: Metabook
- Token Symbol: Metabook
- Logo: (logo should be uploaded under assets/mainnet/<D73ZAaGZnsvM4gJUTJ1BfKkPH8zmyv5om97vfwu4MTkD>/\*.<png/svg>)
- Link to the official homepage of token: https://metabooktoken.io/
- Coingecko ID if available NA

### CODE REVIEW

**Comment by AyoCodess** [comment]
let me no if there are any issues, thanks.

**Comment by AyoCodess** [comment]
does this mean my commits were  a success and our token will be added?

**Comment by AceBarrett** [comment]
Foster Forward

**Comment by keone** [comment]
this is a massive diff (possibly due to main changing a lot in the last month). please rebase your commit against the current version of main and then open an issue

**Pull request closed without merging**
