### PR TITLE
Add FYFY Token

### PR DESCRIPTION
**Pull request by vamise**
Add FYFY Token

- Token Address:  vkG3Qrz6vCWjzDt5yCLEKYMYZ8hFZ27dmKe92btaZE3
- Token Name: FYFY Token
- Token Symbol: FYFY
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/vkG3Qrz6vCWjzDt5yCLEKYMYZ8hFZ27dmKe92btaZE3/logo.png
- Link to the official homepage of token: https://fyfy.io

### CODE REVIEW

**Comment by vamise** [comment]
Fix

**Comment by J-a-m-e-s-o-n** [comment]
I can help resolve automerge issues. 

Feel free to check out J-a-m-e-s-o-n/token-list#1

**Comment by vamise** [comment]
Try to solve automerge problem

**Comment by vamise** [comment]
Add FYFY Token Logo

**Comment by vamise** [comment]
Fix logoURI tokenlist.json

**Comment by vamise** [comment]
Removed Coingecko ID from extension / Added white paper link

**Pull request closed without merging**
