### PR TITLE
Update solana.tokenlist.json

### PR DESCRIPTION
**Pull request by solanasail**
- [ ] I will not ping on Discord/Twitter/email about this pull request.

PRs are reviewed in bulk and and can take up to two weeks to be merged.

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR. 
DON'T modify any other token on the list.

At minimum each entry should have
* Token Address: GSaiLQxREzaxUcE3v28HxBacoUQPZNtXx1eQsCFsX9Bg
* Token Name: gSAIL
* Token Symbol: gSAIL
* Logo: https://ipfs.io/ipfs/QmNNt1xoyB7gwjLLzUYMELYGY277ZzZXJw1vhnZW18Wozq?filename=logo_GSAIL.png
* Link to the official homepage of token: https://www.solanasail.com
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): N/A

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
can you point to logo in this repository

**Comment by solanasail** [comment]
Sure, logo point now in the repository @bartosz-lipinski 😉

**Comment by solanasail** [comment]
Hello @oJshua, May I ask you to merge our PR ?
Thanks in advance for your support 😉

**Comment by solanasail** [comment]
Sync with latest merge

**Pull request merged**
