### PR TITLE
Add VPE

### PR DESCRIPTION
**Pull request by VPOWERSWAP**
- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR

At minimum each entry should have
* Token Address: 35KgRun5UMT2Kjtjw4cNG1tXHcgBxuxji6Yp6ciz7yX7
* Token Name: VPOWER
* Token Symbol: VPE
* Logo: https://cdn.jsdelivr.net/gh/VPOWERSWAP/VPE@main/logo.png
* Link to the official homepage of token: https://vpowerswap.com/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
please store logo in this repo under assets/mainnet/<mint>

**Comment by VPOWERSWAP** [comment]
logo has been added please look into this pull request also

**Comment by bartosz-lipinski** [comment]
> logo has been added please look into this pull request also

Json file needs to use added logo, also please resolve conflicts

**Comment by VPOWERSWAP** [comment]
All issues have been resolved

**Comment by VPOWERSWAP** [comment]
@bartosz-lipinski am I good to go?

**Comment by VPOWERSWAP** [comment]
@bartosz-lipinski i have done all I'm supposed to do, what else is delaying the merging, this PR has been open for 19days.

**Comment by oJshua** [comment]
@VPOWERSWAP logoURI just needs to be prepended with `https://raw.githubusercontent.com/solana-labs/token-list/main/`.

**Comment by VPOWERSWAP** [comment]
this is the error i get everytime in the mergepal-merge
"Resource not accessible by integration"

**Comment by VPOWERSWAP** [comment]
@oJshua

**Comment by oJshua** [comment]
@VPOWERSWAP Sorry about that we were working on an automerge feature. Can you revert back to https://github.com/solana-labs/token-list/pull/411/commits/c2fbededd62e889ea09814589a5dcb3c1d95e988 . It's not necessary to run the release script. Let me know if you have questions!

**Comment by VPOWERSWAP** [comment]
@oJshua Git revert c2fbede should do right? I don't want to mess up things🥴

**Comment by oJshua** [comment]
Normally it's not advised to modify the history in a git repo, but since this is your local branch you could do:
`git reset --hard c2fbede`. After that, make sure you rebase or merge against the latest token-list `upstream/main` branch. Then you can do a git push with `--force` to update the origin. Does that make sense?

**Comment by VPOWERSWAP** [comment]
@oJshua i think i have done somethings, but i don't know y it keeps running the merge script itself when i resolve conflicts

**Pull request merged**
