### PR TITLE
Add DWT token

### PR DESCRIPTION
**Pull request by DARK-WEB-TOKEN**
Website is on the way.

- [x] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: cREsCN7KAyXcBG2xZc8qrfNHMRgC3MhTb4n3jBnNysv
* Token Name: Dark Web Token
* Token Symbol: DWT
* Logo: https://cdn.jsdelivr.net/gh/DARK-WEB-TOKEN/DWT-LOGO/logo.png
* Link to the official homepage of token: https://darkwebtoken.live
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by DARK-WEB-TOKEN** [comment]
@bartosz-lipinski i know you are really bussy but why so much delay. Did i do something wrong ?

**Comment by oJshua** [comment]
@DARK-WEB-TOKEN could you resolve the conflicting files? Thanks!

**Comment by DARK-WEB-TOKEN** [comment]
@oJshua conflicts have been resolved.

**Comment by oJshua** [comment]
https://github.com/solana-labs/token-list/pull/216

**Pull request closed without merging**
