### PR TITLE
Add new Token SDA to  tokenlist.json

### PR DESCRIPTION
**Pull request by SolADA12**
- [ ] I will not ping on Discord/Twitter/email about this pull request.

PRs are reviewed in bulk and and can take up to two weeks to be merged.

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR. 
DON'T modify any other token on the list.

At minimum each entry should have
* Token Address: DAhyNwD9bsMkcgXHzCvVCVimkpeRwc6bv9i47UuuQAo3
* Token Name: SolADA
* Token Symbol: SDA
* Logo: https://1.bp.blogspot.com/-i0y17yXzNEs/YLCZ2wnk2GI/AAAAAAAAerU/uM0IXaQ7WvcPYFpVoQWisfjtszXFcpWMQCLcBGAsYHQ/s1024/SolADA%2BToken.png
* Link to the official homepage of token: http://solada.unaux.com/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
Use https for the links, and store logo in this repository

**Comment by SolADA12** [comment]
Ok sir. We are updating. Do i need to open new pull request or you will consider this one only? If i made the changes

**Comment by bartosz-lipinski** [comment]
> Ok sir. We are updating. Do i need to open new pull request or you will consider this one only? If i made the changes

same one is fine

**Comment by bartosz-lipinski** [comment]
please open new pull request with, logo stored in this repo.

**Pull request closed without merging**
