### PR TITLE
Add CRYN token

### PR DESCRIPTION
**Pull request by solanacrayon**
- [x] I will not ping on Discord/Twitter/email about this pull request.

PRs are reviewed in bulk and and can take up to two weeks to be merged.

**Please provide the following information for your token.**

Please include change to the `src/tokens/solana.tokenlist.json` file in the PR. 
DON'T modify any other token on the list.

At minimum each entry should have
* Token Address: 5pXLmRJyfrTDYMCp1xyiqRDcbb7vYjYiMYzhBza2ht62
* Token Name: Crayon
* Token Symbol: CRYN
* Logo: https://github.com/solanacrayon/solanacrayon/blob/main/crayon_logo.png
* Link to the official homepage of token: https://solanacrayon.com
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Review by solanacrayon — COMMENTED** [review]
done

**Comment by UnyillIDN17** [comment]
Let's grow together sir 🙂

**Comment by UnyillIDN17** [comment]
have you created a telegram group for community announcements, sir? and can i join?

**Comment by solanacrayon** [comment]
> have you created a telegram group for community announcements, sir? and can i join?

not yet

**Comment by UnyillIDN17** [comment]
okay I'm waiting for you. if you need help, can I help you?

Pada tanggal Sab, 10 Jul 2021 6.59 AM, solanacrayon <
***@***.***> menulis:

**Comment by UnyillIDN17** [comment]
okay I'm waiting for you. if you need help, I canhelp you

Pada tanggal Sab, 10 Jul 2021 6.59 AM, solanacrayon <
***@***.***> menulis:

**Comment by solanacrayon** [comment]
Hi team, Could you check our PR and approve our request.
Thank's 🙂
@mvines

**Comment by UnyillIDN17** [comment]
Ok, I will check.

Pada tanggal Sen, 12 Jul 2021 11.23 AM, solanacrayon <
***@***.***> menulis:

**Comment by UnyillIDN17** [comment]
does crayon already have a telegram group? I think telegram can also strengthen the community

**Review by solanacrayon — COMMENTED** [review]
waiting PR Approval

**Pull request merged**
