### PR TITLE
Add NINJA token

### PR DESCRIPTION
**Pull request by yuzu-ninjaprotocol**
- [x] I will not ping the Discord about this pull request.

Token Address: Ae1aeYK9WrB2kP29jJU4aUUK7Y1vzsGNZFKoe4BG2h6P
Token Name: NINJA
Token Symbol: NINJA
Logo: https://raw.githubusercontent.com/yuzu-ninjaprotocol/ninjaprotocol/main/NINJA%20Token.svg
Link to the official homepage of token: http://ninjaprotocol.io

Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by yuzu-ninjaprotocol** [comment]
If there is an issue. Please let me know.  I will fix it.

**Comment by bartosz-lipinski** [comment]
image doesnt link to raw file.

**Comment by yuzu-ninjaprotocol** [comment]
> image doesnt link to raw file.

Hello, I updated the image link.  It is now using the github raw.  Also it is a bigger image file, using SVG. If this does not work. I can change, just let me know.  Thankyou.

**Comment by bartosz-lipinski** [comment]
> > image doesnt link to raw file.
> 
> Hello, I updated the image link. It is now using the github raw. Also it is a bigger image file, using SVG. If this does not work. I can change, just let me know. Thankyou.

**Pull request closed without merging**
