### PR TITLE
add saving australian koalas token

### PR DESCRIPTION
**Pull request by Saving-Aussie-Wildlife**

### CODE REVIEW

**Comment by zakimzf1** [comment]
I can help refer this https://github.com/zakimzf/profile/pull/1
PS: if you don't need my help.. please ignore this!

**Comment by SolanaTokenMerger** [comment]
If you need somebody to save you time and merge it for you, i'm your guy!!
https://github.com/SolanaTokenMerger

**Comment by Saving-Aussie-Wildlife** [comment]
How can you help ?

Sent from Mail for Windows

**Comment by Saving-Aussie-Wildlife** [comment]
How can you help and do you work for GITHUB ?

Sent from Mail for Windows

**Comment by zakimzf1** [comment]
No i don't work for anyone on GitHub! I am freelancer. I can help you get
your PR automerged into token-list. Contact me on telegram @zakimzf

**Comment by Saving-Aussie-Wildlife** [comment]
I do not have telegram
How do you help 
What access do you require
What payment do you require


Sent from Mail for Windows

**Comment by zakimzf** [comment]
Send me any of your Socials username.. twitter/fb/ig/reddit etc..

**Comment by Saving-Aussie-Wildlife** [comment]
Why can we not use e-mail it is easier for me 




Sent from Mail for Windows

**Comment by zakimzf** [comment]
it will be much difficult to communicate over email! Anyways mail me @ zaki.faiz4@gmail.com

**Pull request closed without merging**
