### PR TITLE
Add Respect (RESP) Token

### PR DESCRIPTION
**Pull request by trapcoins**
Now we have released a fixed supply.

- [ ] I will not ping the Discord about this pull request.

**Please provide the following information for your token.**

Please include change to the src/lib/<env>.json and in the PR

At minimum each entry should have
* Token Address: AZtNYaEAHDBeK5AvdzquZWjc4y8cj5sKWH1keUJGMuPV
* Token Name: RESPECT Coin
* Token Symbol: RESP
* Logo https://static.tildacdn.com/tild3463-3338-4764-b938-363064666431/logo.jpg
* Link to the official homepage of token: https://respect.cash/

### CODE REVIEW

**Comment by trapcoins** [comment]
Now we have fixed supply.  please pull it out soon. The wait takes the second week <3

**Comment by oJshua** [comment]
Thanks @trapcoins. Could you resolve the conflicts and repush?

**Comment by trapcoins** [comment]
> Thanks @trapcoins. Could you resolve the conflicts and repush?
Ok? :)

**Comment by trapcoins** [comment]
what's wrong with the request? explain, I don't understand.

**Pull request closed without merging**
