### PR TITLE
Enable automerge

### PR DESCRIPTION
**Pull request by Community-Dev-Solana**
Enable auto merge.
200+ pull requests waiting for that.
If there any remaining update inform details when enable auto merge to solana community.

### CODE REVIEW

**Review by Community-Dev-Solana — COMMENTED** [review]
Enable auto merge 200+ pull requests waiting for that
**requested review from** @bartosz-lipinski , @rmshea , @CriesofCarrots and @leoluk

**Comment by solcatcoin** [comment]
Yes, please

**Comment by Community-Dev-Solana** [comment]
> Enable auto merge 200+ pull requests waiting for that **requested review from** @bartosz-lipinski , @rmshea , @CriesofCarrots and @leoluk

??

**Comment by leoluk** [comment]
The automerger was disabled because it doesn't work and cause invalid JSON to be merged.

**Pull request closed without merging**
