### PR TITLE
Add Particle Finance token

### PR DESCRIPTION
**Pull request by partifinance**
- [x] I will not ping the Discord about this pull request.

* Token Address: B3Ggjjj3QargPkFTAJiR6BaD8CWKFUaWRXGcDQ1nyeeD
* Token Name: PARTI
* Token Symbol: PARTI
* Logo: https://raw.githubusercontent.com/partifinance/particle-brand/main/particle-finance-logo.png
* Link to the official homepage of token: https://parti.finance
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):

### CODE REVIEW

**Comment by akbarjaya77719** [comment]
Super great ia project

**Comment by mferdi123** [comment]
Wonderful, keep healthy and spirit sir 🔥❤️

**Comment by pMelati** [comment]
The Excellent Project,i love and always support

**Comment by ditoalza** [comment]
lesgooo

**Comment by lenduks** [comment]
Buy now bro, is real and excellent projects good, to the moon
#PARTI @ParticleFinance

**Comment by roberttcerrada** [comment]
Go $PARTI

**Comment by Vanvanel** [comment]
Buy now Parti and feel like you have tokens with amazing projects

**Comment by HadiFab** [comment]
Lovely project

**Comment by akbarjaya77719** [comment]
Not received token ,good luck and solid Community

**Comment by zeedgold** [comment]
This is amazing

**Comment by Suraj999999** [comment]
Good project. Sufficient suppy. NeW ATH WILL COME.

**Comment by DANDEGREAT** [comment]
I never lost hope on this project  I will hold  till lambo

**Pull request merged**
